export const projects = [
      {
      title1: "steph-ai",
      title2: "",
      src: "/projects/ai/hero.gif",
      details: "talk to an ai version of me...",
      slug: "steph-ai",
    },
    {
      title1: "my",
      title2: "portfolio!",
      src: "/projects/portfolio/preloader.png",
      details: "you're looking right at it!",
      slug: "portfolio",
    },
    {
      title1: "optimed",
      title2: "rx",
      src: "/projects/rx/hero.png",
      industry: "Healthcare",
      type: "Full-stack",
      details: "a telehealth web app dedicated to facilitated pharmacy",
      slug: "optimed-rx",
    },  
    {
      title1: "rbc",
      title2: "greensense",
      src: "/projects/rbc/hero.png",
      details: "a mobile app dedicated to eco-concious consumerism",
      slug: "rbc-greensense",
    },
    {
      title1: "tedxtoronto",
      title2: "",
      src: "/projects/ted/hero.gif",
      industry: "NPO",
      type: "Front-end",
      details: "big project, bigger team",
      slug: "tedxtoronto",
    },
  ];